path_classifiers:
  test:
    - unit-tests/files

extraction:
  cpp:
    prepare:
      packages:
        - lzip
        - libgpgme11-dev
    configure:
      command: ./bootstrap && ./configure --disable-doc
